package net.joshuahughes.jnablaslapack;

import com.sun.jna.Library;
import com.sun.jna.Native;
import net.joshuahughes.jnablaslapack.pointer.*;

public interface LapackZH extends Library
{

	public static LapackZH instance = (LapackZH) Native.loadLibrary("liblapack",LapackZH.class);

	public void zhbev_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,INTEGER KD,double[] AB,INTEGER LDAB,double[] W,double[] Z,INTEGER LDZ,double[] WORK,double[] RWORK,INTEGER INFO);
	public void zhbevd_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,INTEGER KD,double[] AB,INTEGER LDAB,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,double[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void zhbevx_(CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,INTEGER KD,double[] AB,INTEGER LDAB,double[] Q,INTEGER LDQ,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,double[] WORK,double[] RWORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void zhbgst_(CHARACTER VECT,CHARACTER UPLO,INTEGER N,INTEGER KA,INTEGER KB,double[] AB,INTEGER LDAB,double[] BB,INTEGER LDBB,double[] X,INTEGER LDX,double[] WORK,double[] RWORK,INTEGER INFO);
	public void zhbgv_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,INTEGER KA,INTEGER KB,double[] AB,INTEGER LDAB,double[] BB,INTEGER LDBB,double[] W,double[] Z,INTEGER LDZ,double[] WORK,double[] RWORK,INTEGER INFO);
	public void zhbgvd_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,INTEGER KA,INTEGER KB,double[] AB,INTEGER LDAB,double[] BB,INTEGER LDBB,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,double[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void zhbgvx_(CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,INTEGER KA,INTEGER KB,double[] AB,INTEGER LDAB,double[] BB,INTEGER LDBB,double[] Q,INTEGER LDQ,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,double[] WORK,double[] RWORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void zhbtrd_(CHARACTER VECT,CHARACTER UPLO,INTEGER N,INTEGER KD,double[] AB,INTEGER LDAB,double[] D,double[] E,double[] Q,INTEGER LDQ,double[] WORK,INTEGER INFO);
	public void zhecon_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,DOUBLE ANORM,DOUBLE RCOND,double[] WORK,INTEGER INFO);
	public void zhecon_rook_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,DOUBLE ANORM,DOUBLE RCOND,double[] WORK,INTEGER INFO);
	public void zheequb_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] S,DOUBLE SCOND,DOUBLE AMAX,double[] WORK,INTEGER INFO);
	public void zheev_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] W,double[] WORK,INTEGER LWORK,double[] RWORK,INTEGER INFO);
	public void zheevd_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] W,double[] WORK,INTEGER LWORK,double[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void zheevr_(CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,int[] ISUPPZ,double[] WORK,INTEGER LWORK,double[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void zheevx_(CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,double[] RWORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void zhegs2_(INTEGER ITYPE,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,INTEGER INFO);
	public void zhegst_(INTEGER ITYPE,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,INTEGER INFO);
	public void zhegv_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] W,double[] WORK,INTEGER LWORK,double[] RWORK,INTEGER INFO);
	public void zhegvd_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] W,double[] WORK,INTEGER LWORK,double[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void zhegvx_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,double[] RWORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void zherfs_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,double[] AF,INTEGER LDAF,int[] IPIV,double[] B,INTEGER LDB,double[] X,INTEGER LDX,double[] FERR,double[] BERR,double[] WORK,double[] RWORK,INTEGER INFO);
	public void zherfsx_(CHARACTER UPLO,CHARACTER EQUED,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,double[] AF,INTEGER LDAF,int[] IPIV,double[] S,double[] B,INTEGER LDB,double[] X,INTEGER LDX,DOUBLE RCOND,double[] BERR,INTEGER N_ERR_BNDS,double[] ERR_BNDS_NORM,double[] ERR_BNDS_COMP,INTEGER NPARAMS,double[] PARAMS,double[] WORK,double[] RWORK,INTEGER INFO);
	public void zhesv_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,int[] IPIV,double[] B,INTEGER LDB,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void zhesvx_(CHARACTER FACT,CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,double[] AF,INTEGER LDAF,int[] IPIV,double[] B,INTEGER LDB,double[] X,INTEGER LDX,DOUBLE RCOND,double[] FERR,double[] BERR,double[] WORK,INTEGER LWORK,double[] RWORK,INTEGER INFO);
	public void zhesvxx_(CHARACTER FACT,CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,double[] AF,INTEGER LDAF,int[] IPIV,CHARACTER EQUED,double[] S,double[] B,INTEGER LDB,double[] X,INTEGER LDX,DOUBLE RCOND,DOUBLE RPVGRW,double[] BERR,INTEGER N_ERR_BNDS,double[] ERR_BNDS_NORM,double[] ERR_BNDS_COMP,INTEGER NPARAMS,double[] PARAMS,double[] WORK,double[] RWORK,INTEGER INFO,LOGICAL LSAME,DOUBLE DLAMCH,DOUBLE ZLA_HERPVGRW);
	public void zhesv_rook_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,int[] IPIV,double[] B,INTEGER LDB,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void zheswapr_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,INTEGER I1,INTEGER I2);
	public void zhetd2_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] D,double[] E,double[] TAU,INTEGER INFO);
	public void zhetf2_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,INTEGER INFO);
	public void zhetf2_rook_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,INTEGER INFO);
	public void zhetrd_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] D,double[] E,double[] TAU,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void zhetrf_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void zhetrf_rook_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void zhetri_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,double[] WORK,INTEGER INFO);
	public void zhetri2_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void zhetri2x_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,double[] WORK,INTEGER NB,INTEGER INFO);
	public void zhetri_rook_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,double[] WORK,INTEGER INFO);
	public void zhetrs_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,int[] IPIV,double[] B,INTEGER LDB,INTEGER INFO);
	public void zhetrs2_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,int[] IPIV,double[] B,INTEGER LDB,double[] WORK,INTEGER INFO);
	public void zhetrs_rook_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,int[] IPIV,double[] B,INTEGER LDB,INTEGER INFO);
	public void zhfrk_(CHARACTER TRANSR,CHARACTER UPLO,CHARACTER TRANS,INTEGER N,INTEGER K,DOUBLE ALPHA,double[] A,INTEGER LDA,DOUBLE BETA,double[] C);
	public void zhgeqz_(CHARACTER JOB,CHARACTER COMPQ,CHARACTER COMPZ,INTEGER N,INTEGER ILO,INTEGER IHI,double[] H,INTEGER LDH,double[] T,INTEGER LDT,double[] ALPHA,double[] BETA,double[] Q,INTEGER LDQ,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,double[] RWORK,INTEGER INFO);
	public void zhpcon_(CHARACTER UPLO,INTEGER N,double[] AP,int[] IPIV,DOUBLE ANORM,DOUBLE RCOND,double[] WORK,INTEGER INFO);
	public void zhpev_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] AP,double[] W,double[] Z,INTEGER LDZ,double[] WORK,double[] RWORK,INTEGER INFO);
	public void zhpevd_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] AP,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,double[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void zhpevx_(CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,double[] AP,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,double[] WORK,double[] RWORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void zhpgst_(INTEGER ITYPE,CHARACTER UPLO,INTEGER N,double[] AP,double[] BP,INTEGER INFO);
	public void zhpgv_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] AP,double[] BP,double[] W,double[] Z,INTEGER LDZ,double[] WORK,double[] RWORK,INTEGER INFO);
	public void zhpgvd_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] AP,double[] BP,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,double[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void zhpgvx_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,double[] AP,double[] BP,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,double[] WORK,double[] RWORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void zhprfs_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] AP,double[] AFP,int[] IPIV,double[] B,INTEGER LDB,double[] X,INTEGER LDX,double[] FERR,double[] BERR,double[] WORK,double[] RWORK,INTEGER INFO);
	public void zhpsv_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] AP,int[] IPIV,double[] B,INTEGER LDB,INTEGER INFO);
	public void zhpsvx_(CHARACTER FACT,CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] AP,double[] AFP,int[] IPIV,double[] B,INTEGER LDB,double[] X,INTEGER LDX,DOUBLE RCOND,double[] FERR,double[] BERR,double[] WORK,double[] RWORK,INTEGER INFO);
	public void zhptrd_(CHARACTER UPLO,INTEGER N,double[] AP,double[] D,double[] E,double[] TAU,INTEGER INFO);
	public void zhptrf_(CHARACTER UPLO,INTEGER N,double[] AP,int[] IPIV,INTEGER INFO);
	public void zhptri_(CHARACTER UPLO,INTEGER N,double[] AP,int[] IPIV,double[] WORK,INTEGER INFO);
	public void zhptrs_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] AP,int[] IPIV,double[] B,INTEGER LDB,INTEGER INFO);
	public void zhsein_(CHARACTER SIDE,CHARACTER EIGSRC,CHARACTER INITV,boolean SELECT,INTEGER N,double[] H,INTEGER LDH,double[] W,double[] VL,INTEGER LDVL,double[] VR,INTEGER LDVR,INTEGER MM,INTEGER M,double[] WORK,double[] RWORK,int[] IFAILL,int[] IFAILR,INTEGER INFO);
	public void zhseqr_(CHARACTER JOB,CHARACTER COMPZ,INTEGER N,INTEGER ILO,INTEGER IHI,double[] H,INTEGER LDH,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,INTEGER INFO);

}