package net.joshuahughes.jnablaslapack;

import com.sun.jna.Library;
import com.sun.jna.Native;
import net.joshuahughes.jnablaslapack.pointer.*;

public interface LapackDT extends Library
{

	public static LapackDT instance = (LapackDT) Native.loadLibrary("liblapack",LapackDT.class);

	public void dtbcon_(CHARACTER NORM,CHARACTER UPLO,CHARACTER DIAG,INTEGER N,INTEGER KD,double[] AB,INTEGER LDAB,DOUBLE RCOND,double[] WORK,int[] IWORK,INTEGER INFO);
	public void dtbrfs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER KD,INTEGER NRHS,double[] AB,INTEGER LDAB,double[] B,INTEGER LDB,double[] X,INTEGER LDX,double[] FERR,double[] BERR,double[] WORK,int[] IWORK,INTEGER INFO);
	public void dtbtrs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER KD,INTEGER NRHS,double[] AB,INTEGER LDAB,double[] B,INTEGER LDB,INTEGER INFO);
	public void dtfsm_(CHARACTER TRANSR,CHARACTER SIDE,CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER M,INTEGER N,DOUBLE ALPHA,double[] A,double[] B,INTEGER LDB);
	public void dtftri_(CHARACTER TRANSR,CHARACTER UPLO,CHARACTER DIAG,INTEGER N,double[] A,INTEGER INFO);
	public void dtfttp_(CHARACTER TRANSR,CHARACTER UPLO,INTEGER N,double[] ARF,double[] AP,INTEGER INFO);
	public void dtfttr_(CHARACTER TRANSR,CHARACTER UPLO,INTEGER N,double[] ARF,double[] A,INTEGER LDA,INTEGER INFO);
	public void dtgevc_(CHARACTER SIDE,CHARACTER HOWMNY,boolean SELECT,INTEGER N,double[] S,INTEGER LDS,double[] P,INTEGER LDP,double[] VL,INTEGER LDVL,double[] VR,INTEGER LDVR,INTEGER MM,INTEGER M,double[] WORK,INTEGER INFO);
	public void dtgex2_(LOGICAL WANTQ,LOGICAL WANTZ,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] Q,INTEGER LDQ,double[] Z,INTEGER LDZ,INTEGER J1,INTEGER N1,INTEGER N2,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void dtgexc_(LOGICAL WANTQ,LOGICAL WANTZ,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] Q,INTEGER LDQ,double[] Z,INTEGER LDZ,INTEGER IFST,INTEGER ILST,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void dtgsen_(INTEGER IJOB,LOGICAL WANTQ,LOGICAL WANTZ,boolean SELECT,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] ALPHAR,double[] ALPHAI,double[] BETA,double[] Q,INTEGER LDQ,double[] Z,INTEGER LDZ,INTEGER M,DOUBLE PL,DOUBLE PR,double[] DIF,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void dtgsja_(CHARACTER JOBU,CHARACTER JOBV,CHARACTER JOBQ,INTEGER M,INTEGER P,INTEGER N,INTEGER K,INTEGER L,double[] A,INTEGER LDA,double[] B,INTEGER LDB,DOUBLE TOLA,DOUBLE TOLB,double[] ALPHA,double[] BETA,double[] U,INTEGER LDU,double[] V,INTEGER LDV,double[] Q,INTEGER LDQ,double[] WORK,INTEGER NCYCLE,INTEGER INFO);
	public void dtgsna_(CHARACTER JOB,CHARACTER HOWMNY,boolean SELECT,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] VL,INTEGER LDVL,double[] VR,INTEGER LDVR,double[] S,double[] DIF,INTEGER MM,INTEGER M,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER INFO);
	public void dtgsy2_(CHARACTER TRANS,INTEGER IJOB,INTEGER M,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] C,INTEGER LDC,double[] D,INTEGER LDD,double[] E,INTEGER LDE,double[] F,INTEGER LDF,DOUBLE SCALE,DOUBLE RDSUM,DOUBLE RDSCAL,int[] IWORK,INTEGER PQ,INTEGER INFO);
	public void dtgsyl_(CHARACTER TRANS,INTEGER IJOB,INTEGER M,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] C,INTEGER LDC,double[] D,INTEGER LDD,double[] E,INTEGER LDE,double[] F,INTEGER LDF,DOUBLE SCALE,DOUBLE DIF,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER INFO);
	public void dtpcon_(CHARACTER NORM,CHARACTER UPLO,CHARACTER DIAG,INTEGER N,double[] AP,DOUBLE RCOND,double[] WORK,int[] IWORK,INTEGER INFO);
	public void dtpmqrt_(CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER K,INTEGER L,INTEGER NB,double[] V,INTEGER LDV,double[] T,INTEGER LDT,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] WORK,INTEGER INFO);
	public void dtpqrt_(INTEGER M,INTEGER N,INTEGER L,INTEGER NB,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] T,INTEGER LDT,double[] WORK,INTEGER INFO);
	public void dtpqrt2_(INTEGER M,INTEGER N,INTEGER L,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] T,INTEGER LDT,INTEGER INFO);
	public void dtprfb_(CHARACTER SIDE,CHARACTER TRANS,CHARACTER DIRECT,CHARACTER STOREV,INTEGER M,INTEGER N,INTEGER K,INTEGER L,double[] V,INTEGER LDV,double[] T,INTEGER LDT,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] WORK,INTEGER LDWORK);
	public void dtprfs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER NRHS,double[] AP,double[] B,INTEGER LDB,double[] X,INTEGER LDX,double[] FERR,double[] BERR,double[] WORK,int[] IWORK,INTEGER INFO);
	public void dtptri_(CHARACTER UPLO,CHARACTER DIAG,INTEGER N,double[] AP,INTEGER INFO);
	public void dtptrs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER NRHS,double[] AP,double[] B,INTEGER LDB,INTEGER INFO);
	public void dtpttf_(CHARACTER TRANSR,CHARACTER UPLO,INTEGER N,double[] AP,double[] ARF,INTEGER INFO);
	public void dtpttr_(CHARACTER UPLO,INTEGER N,double[] AP,double[] A,INTEGER LDA,INTEGER INFO);
	public void dtrcon_(CHARACTER NORM,CHARACTER UPLO,CHARACTER DIAG,INTEGER N,double[] A,INTEGER LDA,DOUBLE RCOND,double[] WORK,int[] IWORK,INTEGER INFO);
	public void dtrevc_(CHARACTER SIDE,CHARACTER HOWMNY,boolean SELECT,INTEGER N,double[] T,INTEGER LDT,double[] VL,INTEGER LDVL,double[] VR,INTEGER LDVR,INTEGER MM,INTEGER M,double[] WORK,INTEGER INFO);
	public void dtrevc3_(CHARACTER SIDE,CHARACTER HOWMNY,boolean SELECT,INTEGER N,double[] T,INTEGER LDT,double[] VL,INTEGER LDVL,double[] VR,INTEGER LDVR,INTEGER MM,INTEGER M,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void dtrexc_(CHARACTER COMPQ,INTEGER N,double[] T,INTEGER LDT,double[] Q,INTEGER LDQ,INTEGER IFST,INTEGER ILST,double[] WORK,INTEGER INFO);
	public void dtrrfs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] X,INTEGER LDX,double[] FERR,double[] BERR,double[] WORK,int[] IWORK,INTEGER INFO);
	public void dtrsen_(CHARACTER JOB,CHARACTER COMPQ,boolean SELECT,INTEGER N,double[] T,INTEGER LDT,double[] Q,INTEGER LDQ,double[] WR,double[] WI,INTEGER M,DOUBLE S,DOUBLE SEP,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void dtrsna_(CHARACTER JOB,CHARACTER HOWMNY,boolean SELECT,INTEGER N,double[] T,INTEGER LDT,double[] VL,INTEGER LDVL,double[] VR,INTEGER LDVR,double[] S,double[] SEP,INTEGER MM,INTEGER M,double[] WORK,INTEGER LDWORK,int[] IWORK,INTEGER INFO);
	public void dtrsyl_(CHARACTER TRANA,CHARACTER TRANB,INTEGER ISGN,INTEGER M,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] C,INTEGER LDC,DOUBLE SCALE,INTEGER INFO);
	public void dtrti2_(CHARACTER UPLO,CHARACTER DIAG,INTEGER N,double[] A,INTEGER LDA,INTEGER INFO);
	public void dtrtri_(CHARACTER UPLO,CHARACTER DIAG,INTEGER N,double[] A,INTEGER LDA,INTEGER INFO);
	public void dtrtrs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,double[] B,INTEGER LDB,INTEGER INFO);
	public void dtrttf_(CHARACTER TRANSR,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] ARF,INTEGER INFO);
	public void dtrttp_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] AP,INTEGER INFO);
	public void dtzrzf_(INTEGER M,INTEGER N,double[] A,INTEGER LDA,double[] TAU,double[] WORK,INTEGER LWORK,INTEGER INFO);

}