package net.joshuahughes.jnablaslapack;

import com.sun.jna.Library;
import com.sun.jna.Native;
import net.joshuahughes.jnablaslapack.pointer.*;

public interface LapackCU extends Library
{

	public static LapackCU instance = (LapackCU) Native.loadLibrary("liblapack",LapackCU.class);

	public void cunbdb_(CHARACTER TRANS,CHARACTER SIGNS,INTEGER M,INTEGER P,INTEGER Q,float[] X11,INTEGER LDX11,float[] X12,INTEGER LDX12,float[] X21,INTEGER LDX21,float[] X22,INTEGER LDX22,float[] THETA,float[] PHI,float[] TAUP1,float[] TAUP2,float[] TAUQ1,float[] TAUQ2,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunbdb1_(INTEGER M,INTEGER P,INTEGER Q,float[] X11,INTEGER LDX11,float[] X21,INTEGER LDX21,float[] THETA,float[] PHI,float[] TAUP1,float[] TAUP2,float[] TAUQ1,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunbdb2_(INTEGER M,INTEGER P,INTEGER Q,float[] X11,INTEGER LDX11,float[] X21,INTEGER LDX21,float[] THETA,float[] PHI,float[] TAUP1,float[] TAUP2,float[] TAUQ1,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunbdb3_(INTEGER M,INTEGER P,INTEGER Q,float[] X11,INTEGER LDX11,float[] X21,INTEGER LDX21,float[] THETA,float[] PHI,float[] TAUP1,float[] TAUP2,float[] TAUQ1,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunbdb4_(INTEGER M,INTEGER P,INTEGER Q,float[] X11,INTEGER LDX11,float[] X21,INTEGER LDX21,float[] THETA,float[] PHI,float[] TAUP1,float[] TAUP2,float[] TAUQ1,float[] PHANTOM,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunbdb5_(INTEGER M1,INTEGER M2,INTEGER N,float[] X1,INTEGER INCX1,float[] X2,INTEGER INCX2,float[] Q1,INTEGER LDQ1,float[] Q2,INTEGER LDQ2,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunbdb6_(INTEGER M1,INTEGER M2,INTEGER N,float[] X1,INTEGER INCX1,float[] X2,INTEGER INCX2,float[] Q1,INTEGER LDQ1,float[] Q2,INTEGER LDQ2,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cuncsd_(CHARACTER JOBU1,CHARACTER JOBU2,CHARACTER JOBV1T,CHARACTER JOBV2T,CHARACTER TRANS,CHARACTER SIGNS,INTEGER M,INTEGER P,INTEGER Q,float[] X11,INTEGER LDX11,float[] X12,INTEGER LDX12,float[] X21,INTEGER LDX21,float[] X22,INTEGER LDX22,float[] THETA,float[] U1,INTEGER LDU1,float[] U2,INTEGER LDU2,float[] V1T,INTEGER LDV1T,float[] V2T,INTEGER LDV2T,float[] WORK,INTEGER LWORK,float[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER INFO);
	public void cuncsd2by1_(CHARACTER JOBU1,CHARACTER JOBU2,CHARACTER JOBV1T,INTEGER M,INTEGER P,INTEGER Q,float[] X11,INTEGER LDX11,float[] X21,INTEGER LDX21,float[] THETA,float[] U1,INTEGER LDU1,float[] U2,INTEGER LDU2,float[] V1T,INTEGER LDV1T,float[] WORK,INTEGER LWORK,float[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER INFO);
	public void cung2l_(INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] WORK,INTEGER INFO);
	public void cung2r_(INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] WORK,INTEGER INFO);
	public void cungbr_(CHARACTER VECT,INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunghr_(INTEGER N,INTEGER ILO,INTEGER IHI,float[] A,INTEGER LDA,float[] TAU,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cungl2_(INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] WORK,INTEGER INFO);
	public void cunglq_(INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cungql_(INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cungqr_(INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cungr2_(INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] WORK,INTEGER INFO);
	public void cungrq_(INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cungtr_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,float[] TAU,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunm22_(CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER N1,INTEGER N2,float[] Q,INTEGER LDQ,float[] C,INTEGER LDC,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunm2l_(CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] C,INTEGER LDC,float[] WORK,INTEGER INFO);
	public void cunm2r_(CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] C,INTEGER LDC,float[] WORK,INTEGER INFO);
	public void cunmbr_(CHARACTER VECT,CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] C,INTEGER LDC,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunmhr_(CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER ILO,INTEGER IHI,float[] A,INTEGER LDA,float[] TAU,float[] C,INTEGER LDC,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunml2_(CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] C,INTEGER LDC,float[] WORK,INTEGER INFO);
	public void cunmlq_(CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] C,INTEGER LDC,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunmql_(CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] C,INTEGER LDC,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunmqr_(CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] C,INTEGER LDC,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunmr2_(CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] C,INTEGER LDC,float[] WORK,INTEGER INFO);
	public void cunmr3_(CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER K,INTEGER L,float[] A,INTEGER LDA,float[] TAU,float[] C,INTEGER LDC,float[] WORK,INTEGER INFO);
	public void cunmrq_(CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER K,float[] A,INTEGER LDA,float[] TAU,float[] C,INTEGER LDC,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunmrz_(CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER K,INTEGER L,float[] A,INTEGER LDA,float[] TAU,float[] C,INTEGER LDC,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cunmtr_(CHARACTER SIDE,CHARACTER UPLO,CHARACTER TRANS,INTEGER M,INTEGER N,float[] A,INTEGER LDA,float[] TAU,float[] C,INTEGER LDC,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cupgtr_(CHARACTER UPLO,INTEGER N,float[] AP,float[] TAU,float[] Q,INTEGER LDQ,float[] WORK,INTEGER INFO);
	public void cupmtr_(CHARACTER SIDE,CHARACTER UPLO,CHARACTER TRANS,INTEGER M,INTEGER N,float[] AP,float[] TAU,float[] C,INTEGER LDC,float[] WORK,INTEGER INFO);

}