package net.joshuahughes.jnablaslapack;

import com.sun.jna.Library;
import com.sun.jna.Native;
import net.joshuahughes.jnablaslapack.pointer.*;

public interface LapackDS extends Library
{

	public static LapackDS instance = (LapackDS) Native.loadLibrary("liblapack",LapackDS.class);

	public void dsbev_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,INTEGER KD,double[] AB,INTEGER LDAB,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER INFO);
	public void dsbevd_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,INTEGER KD,double[] AB,INTEGER LDAB,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void dsbevx_(CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,INTEGER KD,double[] AB,INTEGER LDAB,double[] Q,INTEGER LDQ,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,double[] WORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void dsbgst_(CHARACTER VECT,CHARACTER UPLO,INTEGER N,INTEGER KA,INTEGER KB,double[] AB,INTEGER LDAB,double[] BB,INTEGER LDBB,double[] X,INTEGER LDX,double[] WORK,INTEGER INFO);
	public void dsbgv_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,INTEGER KA,INTEGER KB,double[] AB,INTEGER LDAB,double[] BB,INTEGER LDBB,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER INFO);
	public void dsbgvd_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,INTEGER KA,INTEGER KB,double[] AB,INTEGER LDAB,double[] BB,INTEGER LDBB,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void dsbgvx_(CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,INTEGER KA,INTEGER KB,double[] AB,INTEGER LDAB,double[] BB,INTEGER LDBB,double[] Q,INTEGER LDQ,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,double[] WORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void dsbtrd_(CHARACTER VECT,CHARACTER UPLO,INTEGER N,INTEGER KD,double[] AB,INTEGER LDAB,double[] D,double[] E,double[] Q,INTEGER LDQ,double[] WORK,INTEGER INFO);
	public void dsfrk_(CHARACTER TRANSR,CHARACTER UPLO,CHARACTER TRANS,INTEGER N,INTEGER K,DOUBLE ALPHA,double[] A,INTEGER LDA,DOUBLE BETA,double[] C);
	public void dsgesv_(INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,int[] IPIV,double[] B,INTEGER LDB,double[] X,INTEGER LDX,double[] WORK,float[] SWORK,INTEGER ITER,INTEGER INFO);
	public void dspcon_(CHARACTER UPLO,INTEGER N,double[] AP,int[] IPIV,DOUBLE ANORM,DOUBLE RCOND,double[] WORK,int[] IWORK,INTEGER INFO);
	public void dspev_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] AP,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER INFO);
	public void dspevd_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] AP,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void dspevx_(CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,double[] AP,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,double[] WORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void dspgst_(INTEGER ITYPE,CHARACTER UPLO,INTEGER N,double[] AP,double[] BP,INTEGER INFO);
	public void dspgv_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] AP,double[] BP,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER INFO);
	public void dspgvd_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] AP,double[] BP,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void dspgvx_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,double[] AP,double[] BP,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,double[] WORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void dsposv_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] X,INTEGER LDX,double[] WORK,float[] SWORK,INTEGER ITER,INTEGER INFO);
	public void dsprfs_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] AP,double[] AFP,int[] IPIV,double[] B,INTEGER LDB,double[] X,INTEGER LDX,double[] FERR,double[] BERR,double[] WORK,int[] IWORK,INTEGER INFO);
	public void dspsv_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] AP,int[] IPIV,double[] B,INTEGER LDB,INTEGER INFO);
	public void dspsvx_(CHARACTER FACT,CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] AP,double[] AFP,int[] IPIV,double[] B,INTEGER LDB,double[] X,INTEGER LDX,DOUBLE RCOND,double[] FERR,double[] BERR,double[] WORK,int[] IWORK,INTEGER INFO);
	public void dsptrd_(CHARACTER UPLO,INTEGER N,double[] AP,double[] D,double[] E,double[] TAU,INTEGER INFO);
	public void dsptrf_(CHARACTER UPLO,INTEGER N,double[] AP,int[] IPIV,INTEGER INFO);
	public void dsptri_(CHARACTER UPLO,INTEGER N,double[] AP,int[] IPIV,double[] WORK,INTEGER INFO);
	public void dsptrs_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] AP,int[] IPIV,double[] B,INTEGER LDB,INTEGER INFO);
	public void dstebz_(CHARACTER RANGE,CHARACTER ORDER,INTEGER N,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,double[] D,double[] E,INTEGER M,INTEGER NSPLIT,double[] W,int[] IBLOCK,int[] ISPLIT,double[] WORK,int[] IWORK,INTEGER INFO);
	public void dstedc_(CHARACTER COMPZ,INTEGER N,double[] D,double[] E,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void dstegr_(CHARACTER JOBZ,CHARACTER RANGE,INTEGER N,double[] D,double[] E,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,int[] ISUPPZ,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void dstein_(INTEGER N,double[] D,double[] E,INTEGER M,double[] W,int[] IBLOCK,int[] ISPLIT,double[] Z,INTEGER LDZ,double[] WORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void dstemr_(CHARACTER JOBZ,CHARACTER RANGE,INTEGER N,double[] D,double[] E,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,INTEGER M,double[] W,double[] Z,INTEGER LDZ,INTEGER NZC,int[] ISUPPZ,LOGICAL TRYRAC,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void dsteqr_(CHARACTER COMPZ,INTEGER N,double[] D,double[] E,double[] Z,INTEGER LDZ,double[] WORK,INTEGER INFO);
	public void dsterf_(INTEGER N,double[] D,double[] E,INTEGER INFO);
	public void dstev_(CHARACTER JOBZ,INTEGER N,double[] D,double[] E,double[] Z,INTEGER LDZ,double[] WORK,INTEGER INFO);
	public void dstevd_(CHARACTER JOBZ,INTEGER N,double[] D,double[] E,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void dstevr_(CHARACTER JOBZ,CHARACTER RANGE,INTEGER N,double[] D,double[] E,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,int[] ISUPPZ,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void dstevx_(CHARACTER JOBZ,CHARACTER RANGE,INTEGER N,double[] D,double[] E,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,double[] WORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void dsycon_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,DOUBLE ANORM,DOUBLE RCOND,double[] WORK,int[] IWORK,INTEGER INFO);
	public void dsyconv_(CHARACTER UPLO,CHARACTER WAY,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,double[] E,INTEGER INFO);
	public void dsycon_rook_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,DOUBLE ANORM,DOUBLE RCOND,double[] WORK,int[] IWORK,INTEGER INFO);
	public void dsyequb_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] S,DOUBLE SCOND,DOUBLE AMAX,double[] WORK,INTEGER INFO);
	public void dsyev_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] W,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void dsyevd_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] W,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void dsyevr_(CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,int[] ISUPPZ,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void dsyevx_(CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void dsygs2_(INTEGER ITYPE,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,INTEGER INFO);
	public void dsygst_(INTEGER ITYPE,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,INTEGER INFO);
	public void dsygv_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] W,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void dsygvd_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,double[] W,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void dsygvx_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] B,INTEGER LDB,DOUBLE VL,DOUBLE VU,INTEGER IL,INTEGER IU,DOUBLE ABSTOL,INTEGER M,double[] W,double[] Z,INTEGER LDZ,double[] WORK,INTEGER LWORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void dsyrfs_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,double[] AF,INTEGER LDAF,int[] IPIV,double[] B,INTEGER LDB,double[] X,INTEGER LDX,double[] FERR,double[] BERR,double[] WORK,int[] IWORK,INTEGER INFO);
	public void dsyrfsx_(CHARACTER UPLO,CHARACTER EQUED,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,double[] AF,INTEGER LDAF,int[] IPIV,double[] S,double[] B,INTEGER LDB,double[] X,INTEGER LDX,DOUBLE RCOND,double[] BERR,INTEGER N_ERR_BNDS,double[] ERR_BNDS_NORM,double[] ERR_BNDS_COMP,INTEGER NPARAMS,double[] PARAMS,double[] WORK,int[] IWORK,INTEGER INFO);
	public void dsysv_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,int[] IPIV,double[] B,INTEGER LDB,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void dsysvx_(CHARACTER FACT,CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,double[] AF,INTEGER LDAF,int[] IPIV,double[] B,INTEGER LDB,double[] X,INTEGER LDX,DOUBLE RCOND,double[] FERR,double[] BERR,double[] WORK,INTEGER LWORK,int[] IWORK,INTEGER INFO);
	public void dsysvxx_(CHARACTER FACT,CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,double[] AF,INTEGER LDAF,int[] IPIV,CHARACTER EQUED,double[] S,double[] B,INTEGER LDB,double[] X,INTEGER LDX,DOUBLE RCOND,DOUBLE RPVGRW,double[] BERR,INTEGER N_ERR_BNDS,double[] ERR_BNDS_NORM,double[] ERR_BNDS_COMP,INTEGER NPARAMS,double[] PARAMS,double[] WORK,int[] IWORK,INTEGER INFO,LOGICAL LSAME,DOUBLE DLAMCH,DOUBLE DLA_SYRPVGRW);
	public void dsysv_rook_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,int[] IPIV,double[] B,INTEGER LDB,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void dsyswapr_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,INTEGER I1,INTEGER I2);
	public void dsytd2_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] D,double[] E,double[] TAU,INTEGER INFO);
	public void dsytf2_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,INTEGER INFO);
	public void dsytf2_rook_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,INTEGER INFO);
	public void dsytrd_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,double[] D,double[] E,double[] TAU,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void dsytrf_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void dsytrf_rook_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void dsytri_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,double[] WORK,INTEGER INFO);
	public void dsytri2_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,double[] WORK,INTEGER LWORK,INTEGER INFO);
	public void dsytri2x_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,double[] WORK,INTEGER NB,INTEGER INFO);
	public void dsytri_rook_(CHARACTER UPLO,INTEGER N,double[] A,INTEGER LDA,int[] IPIV,double[] WORK,INTEGER INFO);
	public void dsytrs_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,int[] IPIV,double[] B,INTEGER LDB,INTEGER INFO);
	public void dsytrs2_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,int[] IPIV,double[] B,INTEGER LDB,double[] WORK,INTEGER INFO);
	public void dsytrs_rook_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,double[] A,INTEGER LDA,int[] IPIV,double[] B,INTEGER LDB,INTEGER INFO);

}