package net.joshuahughes.jnablaslapack;

import com.sun.jna.Library;
import com.sun.jna.Native;
import net.joshuahughes.jnablaslapack.pointer.*;

public interface LapackST extends Library
{

	public static LapackST instance = (LapackST) Native.loadLibrary("liblapack",LapackST.class);

	public void stbcon_(CHARACTER NORM,CHARACTER UPLO,CHARACTER DIAG,INTEGER N,INTEGER KD,float[] AB,INTEGER LDAB,REAL RCOND,float[] WORK,int[] IWORK,INTEGER INFO);
	public void stbrfs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER KD,INTEGER NRHS,float[] AB,INTEGER LDAB,float[] B,INTEGER LDB,float[] X,INTEGER LDX,float[] FERR,float[] BERR,float[] WORK,int[] IWORK,INTEGER INFO);
	public void stbtrs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER KD,INTEGER NRHS,float[] AB,INTEGER LDAB,float[] B,INTEGER LDB,INTEGER INFO);
	public void stfsm_(CHARACTER TRANSR,CHARACTER SIDE,CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER M,INTEGER N,REAL ALPHA,float[] A,float[] B,INTEGER LDB);
	public void stftri_(CHARACTER TRANSR,CHARACTER UPLO,CHARACTER DIAG,INTEGER N,float[] A,INTEGER INFO);
	public void stfttp_(CHARACTER TRANSR,CHARACTER UPLO,INTEGER N,float[] ARF,float[] AP,INTEGER INFO);
	public void stfttr_(CHARACTER TRANSR,CHARACTER UPLO,INTEGER N,float[] ARF,float[] A,INTEGER LDA,INTEGER INFO);
	public void stgevc_(CHARACTER SIDE,CHARACTER HOWMNY,boolean SELECT,INTEGER N,float[] S,INTEGER LDS,float[] P,INTEGER LDP,float[] VL,INTEGER LDVL,float[] VR,INTEGER LDVR,INTEGER MM,INTEGER M,float[] WORK,INTEGER INFO);
	public void stgex2_(LOGICAL WANTQ,LOGICAL WANTZ,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] Q,INTEGER LDQ,float[] Z,INTEGER LDZ,INTEGER J1,INTEGER N1,INTEGER N2,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void stgexc_(LOGICAL WANTQ,LOGICAL WANTZ,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] Q,INTEGER LDQ,float[] Z,INTEGER LDZ,INTEGER IFST,INTEGER ILST,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void stgsen_(INTEGER IJOB,LOGICAL WANTQ,LOGICAL WANTZ,boolean SELECT,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] ALPHAR,float[] ALPHAI,float[] BETA,float[] Q,INTEGER LDQ,float[] Z,INTEGER LDZ,INTEGER M,REAL PL,REAL PR,float[] DIF,float[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void stgsja_(CHARACTER JOBU,CHARACTER JOBV,CHARACTER JOBQ,INTEGER M,INTEGER P,INTEGER N,INTEGER K,INTEGER L,float[] A,INTEGER LDA,float[] B,INTEGER LDB,REAL TOLA,REAL TOLB,float[] ALPHA,float[] BETA,float[] U,INTEGER LDU,float[] V,INTEGER LDV,float[] Q,INTEGER LDQ,float[] WORK,INTEGER NCYCLE,INTEGER INFO);
	public void stgsna_(CHARACTER JOB,CHARACTER HOWMNY,boolean SELECT,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] VL,INTEGER LDVL,float[] VR,INTEGER LDVR,float[] S,float[] DIF,INTEGER MM,INTEGER M,float[] WORK,INTEGER LWORK,int[] IWORK,INTEGER INFO);
	public void stgsy2_(CHARACTER TRANS,INTEGER IJOB,INTEGER M,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] C,INTEGER LDC,float[] D,INTEGER LDD,float[] E,INTEGER LDE,float[] F,INTEGER LDF,REAL SCALE,REAL RDSUM,REAL RDSCAL,int[] IWORK,INTEGER PQ,INTEGER INFO);
	public void stgsyl_(CHARACTER TRANS,INTEGER IJOB,INTEGER M,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] C,INTEGER LDC,float[] D,INTEGER LDD,float[] E,INTEGER LDE,float[] F,INTEGER LDF,REAL SCALE,REAL DIF,float[] WORK,INTEGER LWORK,int[] IWORK,INTEGER INFO);
	public void stpcon_(CHARACTER NORM,CHARACTER UPLO,CHARACTER DIAG,INTEGER N,float[] AP,REAL RCOND,float[] WORK,int[] IWORK,INTEGER INFO);
	public void stpmqrt_(CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER K,INTEGER L,INTEGER NB,float[] V,INTEGER LDV,float[] T,INTEGER LDT,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] WORK,INTEGER INFO);
	public void stpqrt_(INTEGER M,INTEGER N,INTEGER L,INTEGER NB,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] T,INTEGER LDT,float[] WORK,INTEGER INFO);
	public void stpqrt2_(INTEGER M,INTEGER N,INTEGER L,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] T,INTEGER LDT,INTEGER INFO);
	public void stprfb_(CHARACTER SIDE,CHARACTER TRANS,CHARACTER DIRECT,CHARACTER STOREV,INTEGER M,INTEGER N,INTEGER K,INTEGER L,float[] V,INTEGER LDV,float[] T,INTEGER LDT,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] WORK,INTEGER LDWORK);
	public void stprfs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER NRHS,float[] AP,float[] B,INTEGER LDB,float[] X,INTEGER LDX,float[] FERR,float[] BERR,float[] WORK,int[] IWORK,INTEGER INFO);
	public void stptri_(CHARACTER UPLO,CHARACTER DIAG,INTEGER N,float[] AP,INTEGER INFO);
	public void stptrs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER NRHS,float[] AP,float[] B,INTEGER LDB,INTEGER INFO);
	public void stpttf_(CHARACTER TRANSR,CHARACTER UPLO,INTEGER N,float[] AP,float[] ARF,INTEGER INFO);
	public void stpttr_(CHARACTER UPLO,INTEGER N,float[] AP,float[] A,INTEGER LDA,INTEGER INFO);
	public void strcon_(CHARACTER NORM,CHARACTER UPLO,CHARACTER DIAG,INTEGER N,float[] A,INTEGER LDA,REAL RCOND,float[] WORK,int[] IWORK,INTEGER INFO);
	public void strevc_(CHARACTER SIDE,CHARACTER HOWMNY,boolean SELECT,INTEGER N,float[] T,INTEGER LDT,float[] VL,INTEGER LDVL,float[] VR,INTEGER LDVR,INTEGER MM,INTEGER M,float[] WORK,INTEGER INFO);
	public void strevc3_(CHARACTER SIDE,CHARACTER HOWMNY,boolean SELECT,INTEGER N,float[] T,INTEGER LDT,float[] VL,INTEGER LDVL,float[] VR,INTEGER LDVR,INTEGER MM,INTEGER M,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void strexc_(CHARACTER COMPQ,INTEGER N,float[] T,INTEGER LDT,float[] Q,INTEGER LDQ,INTEGER IFST,INTEGER ILST,float[] WORK,INTEGER INFO);
	public void strrfs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER NRHS,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] X,INTEGER LDX,float[] FERR,float[] BERR,float[] WORK,int[] IWORK,INTEGER INFO);
	public void strsen_(CHARACTER JOB,CHARACTER COMPQ,boolean SELECT,INTEGER N,float[] T,INTEGER LDT,float[] Q,INTEGER LDQ,float[] WR,float[] WI,INTEGER M,REAL S,REAL SEP,float[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void strsna_(CHARACTER JOB,CHARACTER HOWMNY,boolean SELECT,INTEGER N,float[] T,INTEGER LDT,float[] VL,INTEGER LDVL,float[] VR,INTEGER LDVR,float[] S,float[] SEP,INTEGER MM,INTEGER M,float[] WORK,INTEGER LDWORK,int[] IWORK,INTEGER INFO);
	public void strsyl_(CHARACTER TRANA,CHARACTER TRANB,INTEGER ISGN,INTEGER M,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] C,INTEGER LDC,REAL SCALE,INTEGER INFO);
	public void strti2_(CHARACTER UPLO,CHARACTER DIAG,INTEGER N,float[] A,INTEGER LDA,INTEGER INFO);
	public void strtri_(CHARACTER UPLO,CHARACTER DIAG,INTEGER N,float[] A,INTEGER LDA,INTEGER INFO);
	public void strtrs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER NRHS,float[] A,INTEGER LDA,float[] B,INTEGER LDB,INTEGER INFO);
	public void strttf_(CHARACTER TRANSR,CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,float[] ARF,INTEGER INFO);
	public void strttp_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,float[] AP,INTEGER INFO);
	public void stzrzf_(INTEGER M,INTEGER N,float[] A,INTEGER LDA,float[] TAU,float[] WORK,INTEGER LWORK,INTEGER INFO);

}