package net.joshuahughes.jnablaslapack;

import com.sun.jna.Library;
import com.sun.jna.Native;
import net.joshuahughes.jnablaslapack.pointer.*;

public interface LapackCH extends Library
{

	public static LapackCH instance = (LapackCH) Native.loadLibrary("liblapack",LapackCH.class);

	public void chbev_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,INTEGER KD,float[] AB,INTEGER LDAB,float[] W,float[] Z,INTEGER LDZ,float[] WORK,float[] RWORK,INTEGER INFO);
	public void chbevd_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,INTEGER KD,float[] AB,INTEGER LDAB,float[] W,float[] Z,INTEGER LDZ,float[] WORK,INTEGER LWORK,float[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void chbevx_(CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,INTEGER KD,float[] AB,INTEGER LDAB,float[] Q,INTEGER LDQ,REAL VL,REAL VU,INTEGER IL,INTEGER IU,REAL ABSTOL,INTEGER M,float[] W,float[] Z,INTEGER LDZ,float[] WORK,float[] RWORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void chbgst_(CHARACTER VECT,CHARACTER UPLO,INTEGER N,INTEGER KA,INTEGER KB,float[] AB,INTEGER LDAB,float[] BB,INTEGER LDBB,float[] X,INTEGER LDX,float[] WORK,float[] RWORK,INTEGER INFO);
	public void chbgv_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,INTEGER KA,INTEGER KB,float[] AB,INTEGER LDAB,float[] BB,INTEGER LDBB,float[] W,float[] Z,INTEGER LDZ,float[] WORK,float[] RWORK,INTEGER INFO);
	public void chbgvd_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,INTEGER KA,INTEGER KB,float[] AB,INTEGER LDAB,float[] BB,INTEGER LDBB,float[] W,float[] Z,INTEGER LDZ,float[] WORK,INTEGER LWORK,float[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void chbgvx_(CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,INTEGER KA,INTEGER KB,float[] AB,INTEGER LDAB,float[] BB,INTEGER LDBB,float[] Q,INTEGER LDQ,REAL VL,REAL VU,INTEGER IL,INTEGER IU,REAL ABSTOL,INTEGER M,float[] W,float[] Z,INTEGER LDZ,float[] WORK,float[] RWORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void chbtrd_(CHARACTER VECT,CHARACTER UPLO,INTEGER N,INTEGER KD,float[] AB,INTEGER LDAB,float[] D,float[] E,float[] Q,INTEGER LDQ,float[] WORK,INTEGER INFO);
	public void checon_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,int[] IPIV,REAL ANORM,REAL RCOND,float[] WORK,INTEGER INFO);
	public void checon_rook_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,int[] IPIV,REAL ANORM,REAL RCOND,float[] WORK,INTEGER INFO);
	public void cheequb_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,float[] S,REAL SCOND,REAL AMAX,float[] WORK,INTEGER INFO);
	public void cheev_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,float[] W,float[] WORK,INTEGER LWORK,float[] RWORK,INTEGER INFO);
	public void cheevd_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,float[] W,float[] WORK,INTEGER LWORK,float[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void cheevr_(CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,REAL VL,REAL VU,INTEGER IL,INTEGER IU,REAL ABSTOL,INTEGER M,float[] W,float[] Z,INTEGER LDZ,int[] ISUPPZ,float[] WORK,INTEGER LWORK,float[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void cheevx_(CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,REAL VL,REAL VU,INTEGER IL,INTEGER IU,REAL ABSTOL,INTEGER M,float[] W,float[] Z,INTEGER LDZ,float[] WORK,INTEGER LWORK,float[] RWORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void chegs2_(INTEGER ITYPE,CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,INTEGER INFO);
	public void chegst_(INTEGER ITYPE,CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,INTEGER INFO);
	public void chegv_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] W,float[] WORK,INTEGER LWORK,float[] RWORK,INTEGER INFO);
	public void chegvd_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] W,float[] WORK,INTEGER LWORK,float[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void chegvx_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,REAL VL,REAL VU,INTEGER IL,INTEGER IU,REAL ABSTOL,INTEGER M,float[] W,float[] Z,INTEGER LDZ,float[] WORK,INTEGER LWORK,float[] RWORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void cherfs_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,float[] A,INTEGER LDA,float[] AF,INTEGER LDAF,int[] IPIV,float[] B,INTEGER LDB,float[] X,INTEGER LDX,float[] FERR,float[] BERR,float[] WORK,float[] RWORK,INTEGER INFO);
	public void cherfsx_(CHARACTER UPLO,CHARACTER EQUED,INTEGER N,INTEGER NRHS,float[] A,INTEGER LDA,float[] AF,INTEGER LDAF,int[] IPIV,float[] S,float[] B,INTEGER LDB,float[] X,INTEGER LDX,REAL RCOND,float[] BERR,INTEGER N_ERR_BNDS,float[] ERR_BNDS_NORM,float[] ERR_BNDS_COMP,INTEGER NPARAMS,float[] PARAMS,float[] WORK,float[] RWORK,INTEGER INFO);
	public void chesv_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,float[] A,INTEGER LDA,int[] IPIV,float[] B,INTEGER LDB,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void chesvx_(CHARACTER FACT,CHARACTER UPLO,INTEGER N,INTEGER NRHS,float[] A,INTEGER LDA,float[] AF,INTEGER LDAF,int[] IPIV,float[] B,INTEGER LDB,float[] X,INTEGER LDX,REAL RCOND,float[] FERR,float[] BERR,float[] WORK,INTEGER LWORK,float[] RWORK,INTEGER INFO);
	public void chesvxx_(CHARACTER FACT,CHARACTER UPLO,INTEGER N,INTEGER NRHS,float[] A,INTEGER LDA,float[] AF,INTEGER LDAF,int[] IPIV,CHARACTER EQUED,float[] S,float[] B,INTEGER LDB,float[] X,INTEGER LDX,REAL RCOND,REAL RPVGRW,float[] BERR,INTEGER N_ERR_BNDS,float[] ERR_BNDS_NORM,float[] ERR_BNDS_COMP,INTEGER NPARAMS,float[] PARAMS,float[] WORK,float[] RWORK,INTEGER INFO,LOGICAL LSAME,REAL SLAMCH,REAL CLA_HERPVGRW);
	public void chesv_rook_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,float[] A,INTEGER LDA,int[] IPIV,float[] B,INTEGER LDB,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void cheswapr_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,INTEGER I1,INTEGER I2);
	public void chetd2_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,float[] D,float[] E,float[] TAU,INTEGER INFO);
	public void chetf2_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,int[] IPIV,INTEGER INFO);
	public void chetf2_rook_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,int[] IPIV,INTEGER INFO);
	public void chetrd_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,float[] D,float[] E,float[] TAU,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void chetrf_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,int[] IPIV,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void chetrf_rook_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,int[] IPIV,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void chetri_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,int[] IPIV,float[] WORK,INTEGER INFO);
	public void chetri2_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,int[] IPIV,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void chetri2x_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,int[] IPIV,float[] WORK,INTEGER NB,INTEGER INFO);
	public void chetri_rook_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,int[] IPIV,float[] WORK,INTEGER INFO);
	public void chetrs_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,float[] A,INTEGER LDA,int[] IPIV,float[] B,INTEGER LDB,INTEGER INFO);
	public void chetrs2_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,float[] A,INTEGER LDA,int[] IPIV,float[] B,INTEGER LDB,float[] WORK,INTEGER INFO);
	public void chetrs_rook_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,float[] A,INTEGER LDA,int[] IPIV,float[] B,INTEGER LDB,INTEGER INFO);
	public void chfrk_(CHARACTER TRANSR,CHARACTER UPLO,CHARACTER TRANS,INTEGER N,INTEGER K,REAL ALPHA,float[] A,INTEGER LDA,REAL BETA,float[] C);
	public void chgeqz_(CHARACTER JOB,CHARACTER COMPQ,CHARACTER COMPZ,INTEGER N,INTEGER ILO,INTEGER IHI,float[] H,INTEGER LDH,float[] T,INTEGER LDT,float[] ALPHA,float[] BETA,float[] Q,INTEGER LDQ,float[] Z,INTEGER LDZ,float[] WORK,INTEGER LWORK,float[] RWORK,INTEGER INFO);
	public char chla_transtype_(INTEGER TRANS);
	public void chpcon_(CHARACTER UPLO,INTEGER N,float[] AP,int[] IPIV,REAL ANORM,REAL RCOND,float[] WORK,INTEGER INFO);
	public void chpev_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,float[] AP,float[] W,float[] Z,INTEGER LDZ,float[] WORK,float[] RWORK,INTEGER INFO);
	public void chpevd_(CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,float[] AP,float[] W,float[] Z,INTEGER LDZ,float[] WORK,INTEGER LWORK,float[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void chpevx_(CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,float[] AP,REAL VL,REAL VU,INTEGER IL,INTEGER IU,REAL ABSTOL,INTEGER M,float[] W,float[] Z,INTEGER LDZ,float[] WORK,float[] RWORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void chpgst_(INTEGER ITYPE,CHARACTER UPLO,INTEGER N,float[] AP,float[] BP,INTEGER INFO);
	public void chpgv_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,float[] AP,float[] BP,float[] W,float[] Z,INTEGER LDZ,float[] WORK,float[] RWORK,INTEGER INFO);
	public void chpgvd_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER UPLO,INTEGER N,float[] AP,float[] BP,float[] W,float[] Z,INTEGER LDZ,float[] WORK,INTEGER LWORK,float[] RWORK,INTEGER LRWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void chpgvx_(INTEGER ITYPE,CHARACTER JOBZ,CHARACTER RANGE,CHARACTER UPLO,INTEGER N,float[] AP,float[] BP,REAL VL,REAL VU,INTEGER IL,INTEGER IU,REAL ABSTOL,INTEGER M,float[] W,float[] Z,INTEGER LDZ,float[] WORK,float[] RWORK,int[] IWORK,int[] IFAIL,INTEGER INFO);
	public void chprfs_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,float[] AP,float[] AFP,int[] IPIV,float[] B,INTEGER LDB,float[] X,INTEGER LDX,float[] FERR,float[] BERR,float[] WORK,float[] RWORK,INTEGER INFO);
	public void chpsv_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,float[] AP,int[] IPIV,float[] B,INTEGER LDB,INTEGER INFO);
	public void chpsvx_(CHARACTER FACT,CHARACTER UPLO,INTEGER N,INTEGER NRHS,float[] AP,float[] AFP,int[] IPIV,float[] B,INTEGER LDB,float[] X,INTEGER LDX,REAL RCOND,float[] FERR,float[] BERR,float[] WORK,float[] RWORK,INTEGER INFO);
	public void chptrd_(CHARACTER UPLO,INTEGER N,float[] AP,float[] D,float[] E,float[] TAU,INTEGER INFO);
	public void chptrf_(CHARACTER UPLO,INTEGER N,float[] AP,int[] IPIV,INTEGER INFO);
	public void chptri_(CHARACTER UPLO,INTEGER N,float[] AP,int[] IPIV,float[] WORK,INTEGER INFO);
	public void chptrs_(CHARACTER UPLO,INTEGER N,INTEGER NRHS,float[] AP,int[] IPIV,float[] B,INTEGER LDB,INTEGER INFO);
	public void chsein_(CHARACTER SIDE,CHARACTER EIGSRC,CHARACTER INITV,boolean SELECT,INTEGER N,float[] H,INTEGER LDH,float[] W,float[] VL,INTEGER LDVL,float[] VR,INTEGER LDVR,INTEGER MM,INTEGER M,float[] WORK,float[] RWORK,int[] IFAILL,int[] IFAILR,INTEGER INFO);
	public void chseqr_(CHARACTER JOB,CHARACTER COMPZ,INTEGER N,INTEGER ILO,INTEGER IHI,float[] H,INTEGER LDH,float[] W,float[] Z,INTEGER LDZ,float[] WORK,INTEGER LWORK,INTEGER INFO);

}