package net.joshuahughes.jnablaslapack;

import com.sun.jna.Library;
import com.sun.jna.Native;
import net.joshuahughes.jnablaslapack.pointer.*;

public interface LapackCT extends Library
{

	public static LapackCT instance = (LapackCT) Native.loadLibrary("liblapack",LapackCT.class);

	public void ctbcon_(CHARACTER NORM,CHARACTER UPLO,CHARACTER DIAG,INTEGER N,INTEGER KD,float[] AB,INTEGER LDAB,REAL RCOND,float[] WORK,float[] RWORK,INTEGER INFO);
	public void ctbrfs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER KD,INTEGER NRHS,float[] AB,INTEGER LDAB,float[] B,INTEGER LDB,float[] X,INTEGER LDX,float[] FERR,float[] BERR,float[] WORK,float[] RWORK,INTEGER INFO);
	public void ctbtrs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER KD,INTEGER NRHS,float[] AB,INTEGER LDAB,float[] B,INTEGER LDB,INTEGER INFO);
	public void ctfsm_(CHARACTER TRANSR,CHARACTER SIDE,CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER M,INTEGER N,float[] ALPHA,float[] A,float[] B,INTEGER LDB);
	public void ctftri_(CHARACTER TRANSR,CHARACTER UPLO,CHARACTER DIAG,INTEGER N,float[] A,INTEGER INFO);
	public void ctfttp_(CHARACTER TRANSR,CHARACTER UPLO,INTEGER N,float[] ARF,float[] AP,INTEGER INFO);
	public void ctfttr_(CHARACTER TRANSR,CHARACTER UPLO,INTEGER N,float[] ARF,float[] A,INTEGER LDA,INTEGER INFO);
	public void ctgevc_(CHARACTER SIDE,CHARACTER HOWMNY,boolean SELECT,INTEGER N,float[] S,INTEGER LDS,float[] P,INTEGER LDP,float[] VL,INTEGER LDVL,float[] VR,INTEGER LDVR,INTEGER MM,INTEGER M,float[] WORK,float[] RWORK,INTEGER INFO);
	public void ctgex2_(LOGICAL WANTQ,LOGICAL WANTZ,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] Q,INTEGER LDQ,float[] Z,INTEGER LDZ,INTEGER J1,INTEGER INFO);
	public void ctgexc_(LOGICAL WANTQ,LOGICAL WANTZ,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] Q,INTEGER LDQ,float[] Z,INTEGER LDZ,INTEGER IFST,INTEGER ILST,INTEGER INFO);
	public void ctgsen_(INTEGER IJOB,LOGICAL WANTQ,LOGICAL WANTZ,boolean SELECT,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] ALPHA,float[] BETA,float[] Q,INTEGER LDQ,float[] Z,INTEGER LDZ,INTEGER M,REAL PL,REAL PR,float[] DIF,float[] WORK,INTEGER LWORK,int[] IWORK,INTEGER LIWORK,INTEGER INFO);
	public void ctgsja_(CHARACTER JOBU,CHARACTER JOBV,CHARACTER JOBQ,INTEGER M,INTEGER P,INTEGER N,INTEGER K,INTEGER L,float[] A,INTEGER LDA,float[] B,INTEGER LDB,REAL TOLA,REAL TOLB,float[] ALPHA,float[] BETA,float[] U,INTEGER LDU,float[] V,INTEGER LDV,float[] Q,INTEGER LDQ,float[] WORK,INTEGER NCYCLE,INTEGER INFO);
	public void ctgsna_(CHARACTER JOB,CHARACTER HOWMNY,boolean SELECT,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] VL,INTEGER LDVL,float[] VR,INTEGER LDVR,float[] S,float[] DIF,INTEGER MM,INTEGER M,float[] WORK,INTEGER LWORK,int[] IWORK,INTEGER INFO);
	public void ctgsy2_(CHARACTER TRANS,INTEGER IJOB,INTEGER M,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] C,INTEGER LDC,float[] D,INTEGER LDD,float[] E,INTEGER LDE,float[] F,INTEGER LDF,REAL SCALE,REAL RDSUM,REAL RDSCAL,INTEGER INFO);
	public void ctgsyl_(CHARACTER TRANS,INTEGER IJOB,INTEGER M,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] C,INTEGER LDC,float[] D,INTEGER LDD,float[] E,INTEGER LDE,float[] F,INTEGER LDF,REAL SCALE,REAL DIF,float[] WORK,INTEGER LWORK,int[] IWORK,INTEGER INFO);
	public void ctpcon_(CHARACTER NORM,CHARACTER UPLO,CHARACTER DIAG,INTEGER N,float[] AP,REAL RCOND,float[] WORK,float[] RWORK,INTEGER INFO);
	public void ctpmqrt_(CHARACTER SIDE,CHARACTER TRANS,INTEGER M,INTEGER N,INTEGER K,INTEGER L,INTEGER NB,float[] V,INTEGER LDV,float[] T,INTEGER LDT,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] WORK,INTEGER INFO);
	public void ctpqrt_(INTEGER M,INTEGER N,INTEGER L,INTEGER NB,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] T,INTEGER LDT,float[] WORK,INTEGER INFO);
	public void ctpqrt2_(INTEGER M,INTEGER N,INTEGER L,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] T,INTEGER LDT,INTEGER INFO);
	public void ctprfb_(CHARACTER SIDE,CHARACTER TRANS,CHARACTER DIRECT,CHARACTER STOREV,INTEGER M,INTEGER N,INTEGER K,INTEGER L,float[] V,INTEGER LDV,float[] T,INTEGER LDT,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] WORK,INTEGER LDWORK);
	public void ctprfs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER NRHS,float[] AP,float[] B,INTEGER LDB,float[] X,INTEGER LDX,float[] FERR,float[] BERR,float[] WORK,float[] RWORK,INTEGER INFO);
	public void ctptri_(CHARACTER UPLO,CHARACTER DIAG,INTEGER N,float[] AP,INTEGER INFO);
	public void ctptrs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER NRHS,float[] AP,float[] B,INTEGER LDB,INTEGER INFO);
	public void ctpttf_(CHARACTER TRANSR,CHARACTER UPLO,INTEGER N,float[] AP,float[] ARF,INTEGER INFO);
	public void ctpttr_(CHARACTER UPLO,INTEGER N,float[] AP,float[] A,INTEGER LDA,INTEGER INFO);
	public void ctrcon_(CHARACTER NORM,CHARACTER UPLO,CHARACTER DIAG,INTEGER N,float[] A,INTEGER LDA,REAL RCOND,float[] WORK,float[] RWORK,INTEGER INFO);
	public void ctrevc_(CHARACTER SIDE,CHARACTER HOWMNY,boolean SELECT,INTEGER N,float[] T,INTEGER LDT,float[] VL,INTEGER LDVL,float[] VR,INTEGER LDVR,INTEGER MM,INTEGER M,float[] WORK,float[] RWORK,INTEGER INFO);
	public void ctrevc3_(CHARACTER SIDE,CHARACTER HOWMNY,boolean SELECT,INTEGER N,float[] T,INTEGER LDT,float[] VL,INTEGER LDVL,float[] VR,INTEGER LDVR,INTEGER MM,INTEGER M,float[] WORK,INTEGER LWORK,float[] RWORK,INTEGER LRWORK,INTEGER INFO);
	public void ctrexc_(CHARACTER COMPQ,INTEGER N,float[] T,INTEGER LDT,float[] Q,INTEGER LDQ,INTEGER IFST,INTEGER ILST,INTEGER INFO);
	public void ctrrfs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER NRHS,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] X,INTEGER LDX,float[] FERR,float[] BERR,float[] WORK,float[] RWORK,INTEGER INFO);
	public void ctrsen_(CHARACTER JOB,CHARACTER COMPQ,boolean SELECT,INTEGER N,float[] T,INTEGER LDT,float[] Q,INTEGER LDQ,float[] W,INTEGER M,REAL S,REAL SEP,float[] WORK,INTEGER LWORK,INTEGER INFO);
	public void ctrsna_(CHARACTER JOB,CHARACTER HOWMNY,boolean SELECT,INTEGER N,float[] T,INTEGER LDT,float[] VL,INTEGER LDVL,float[] VR,INTEGER LDVR,float[] S,float[] SEP,INTEGER MM,INTEGER M,float[] WORK,INTEGER LDWORK,float[] RWORK,INTEGER INFO);
	public void ctrsyl_(CHARACTER TRANA,CHARACTER TRANB,INTEGER ISGN,INTEGER M,INTEGER N,float[] A,INTEGER LDA,float[] B,INTEGER LDB,float[] C,INTEGER LDC,REAL SCALE,INTEGER INFO);
	public void ctrti2_(CHARACTER UPLO,CHARACTER DIAG,INTEGER N,float[] A,INTEGER LDA,INTEGER INFO);
	public void ctrtri_(CHARACTER UPLO,CHARACTER DIAG,INTEGER N,float[] A,INTEGER LDA,INTEGER INFO);
	public void ctrtrs_(CHARACTER UPLO,CHARACTER TRANS,CHARACTER DIAG,INTEGER N,INTEGER NRHS,float[] A,INTEGER LDA,float[] B,INTEGER LDB,INTEGER INFO);
	public void ctrttf_(CHARACTER TRANSR,CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,float[] ARF,INTEGER INFO);
	public void ctrttp_(CHARACTER UPLO,INTEGER N,float[] A,INTEGER LDA,float[] AP,INTEGER INFO);
	public void ctzrzf_(INTEGER M,INTEGER N,float[] A,INTEGER LDA,float[] TAU,float[] WORK,INTEGER LWORK,INTEGER INFO);

}